# Generated by Django 3.2 on 2021-11-21 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('ordersapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('C', 'создан'), ('S', 'оплачен'), ('A', 'подтверждён'), ('R', 'отменён')], default='C', max_length=1, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(limit_choices_to={'category__is_active': True, 'is_active': True}, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
