# Generated by Django 3.2 on 2021-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.IntegerField(default=0, verbose_name='Возраст'),
        ),
    ]
