# Generated by Django 3.2 on 2021-11-04 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0003_alter_shopuser_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='age',
            field=models.IntegerField(default=18, verbose_name='Возраст'),
        ),
    ]
