# Generated by Django 3.2.7 on 2021-09-05 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
        migrations.RenameModel(
            old_name='ProductCategories',
            new_name='ProductCategorie',
        ),
    ]
