# Generated by Django 3.2.6 on 2021-09-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
        migrations.AddField(
            model_name='productscategory',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Доступность'),
        ),
    ]
