# Generated by Django 3.2.7 on 2021-09-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210905_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductCategorie',
            new_name='ProductsCategory',
        ),
    ]
