# Generated by Django 3.2 on 2021-12-01 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20211201_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productscategory',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Категория'),
        ),
    ]
